"""Generate the shared National Dex #001-#386 runtime species aliases."""

from __future__ import annotations

import argparse
from pathlib import Path

from import_emerald_shiny_sprites import roster


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    root = args.root.resolve()
    species = roster(root)
    lines = [
        "-- Generated by tools/generate_battle_species_dex.py.",
        "-- Canonical engine species names for National Dex #001-#386.",
        "return {",
    ]
    for number, (name, _) in enumerate(species, 1):
        lines.append(f'  [{number}] = "{name}",')
    lines.append("}")
    destination = root / "data/battle_species_dex_386.lua"
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {destination} with {len(species)} aliases")


if __name__ == "__main__":
    main()
