"""Download Crystal #001-#151 GIFs and build native-resolution PNG atlases.

Artwork is written below assets/battle/front-animated/crystal, which Git
ignores. Only the generated cell/timing metadata belongs in source control.

Default source: https://bluemoonfalls.com/images/sprites/crystal/normal/
"""

from __future__ import annotations

import argparse
import math
import re
import time
import urllib.request
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageSequence


DEFAULT_BASE = "https://bluemoonfalls.com/images/sprites/crystal/normal"
ENTRY = re.compile(
    r'^  ([A-Z0-9_]+) = \{\n'
    r'    front = \{ image = "assets/battle/front-animated/([^/]+)\.png"',
    re.MULTILINE,
)


def species(root: Path) -> list[tuple[str, str]]:
    source = (root / "data" / "animated_battle_sprites.lua").read_text(
        encoding="utf-8"
    )
    entries = ENTRY.findall(source)
    if len(entries) != 151:
        raise ValueError(f"expected 151 Kanto species definitions, got {len(entries)}")
    return entries


def download(url: str, retries: int = 4) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return response.read()
        except Exception:
            if attempt + 1 == retries:
                raise
            time.sleep(1.5 * (attempt + 1))
    raise AssertionError("unreachable")


def convert(raw: bytes, destination: Path, max_columns: int = 16) -> dict:
    with Image.open(BytesIO(raw)) as gif:
        frames, durations = [], []
        for frame in ImageSequence.Iterator(gif):
            durations.append(
                int(frame.info.get("duration", gif.info.get("duration", 100)))
            )
            frames.append(frame.convert("RGBA"))
    if not frames:
        raise ValueError("GIF contains no frames")
    width, height = frames[0].size
    if any(frame.size != (width, height) for frame in frames):
        raise ValueError("GIF frames do not share one logical canvas")
    columns = min(max_columns, len(frames))
    rows = math.ceil(len(frames) / columns)
    sheet = Image.new("RGBA", (columns * width, rows * height))
    for index, frame in enumerate(frames):
        sheet.alpha_composite(
            frame, ((index % columns) * width, (index // columns) * height)
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(destination, optimize=True)
    return {
        "width": width,
        "height": height,
        "columns": columns,
        "frames": len(frames),
        "durations": durations,
    }


def lua_definition(path: str, info: dict) -> str:
    durations = ",".join(map(str, info["durations"]))
    return (
        f'{{ image = "{path}", width = {info["width"]}, '
        f'height = {info["height"]}, columns = {info["columns"]}, '
        f'frames = {info["frames"]}, durations = {{{durations}}} }}'
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--base-url", default=DEFAULT_BASE)
    args = parser.parse_args()
    root = args.root.resolve()
    records = []
    for number, (engine_name, slug) in enumerate(species(root), 1):
        url = f"{args.base_url.rstrip('/')}/{number}.gif"
        relative = f"assets/battle/front-animated/crystal/{slug}.png"
        print(f"[{number:03d}/151] {slug}", flush=True)
        info = convert(download(url), root / relative)
        records.append((engine_name, relative, info))

    lines = [
        "-- Generated by tools/import_crystal_front_sprites.py.",
        "-- Pokemon Crystal animated fronts, National Dex #001-#151.",
        "return {",
    ]
    for engine_name, path, info in records:
        lines.append(f"  {engine_name} = {{")
        lines.append(f"    front = {lua_definition(path, info)},")
        lines.append("  },")
    lines.append("}")
    destination = root / "data" / "animated_battle_sprites_crystal.lua"
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {destination} with {len(records)} animations")


if __name__ == "__main__":
    main()
