"""Import Black/White shiny animated fronts and backs through Dex #386.

Archive titles are tried in canonical bare, male, then female order. Deoxys
Normal, Attack, Defense, and Speed Formes are imported separately; short and
long engine aliases share the same generated atlas metadata.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from import_animated_sprites import convert, lua_definition
from import_gen4_extended_and_shiny_sprites import fetch_candidates
from import_gen5_extended_normal_sprites import canonical_roster


SOURCE = "https://archives.bulbagarden.net/wiki/Special:Redirect/file"


def gendered(prefix: str, dex: str) -> list[str]:
    return [
        f"{prefix} {dex} s.png",
        f"{prefix} {dex} m s.png",
        f"{prefix} {dex} f s.png",
    ]


def import_side(
    source_dir: Path,
    destination: Path,
    base: str,
    prefix: str,
    dex: str,
    slug: str,
    force: bool,
) -> tuple[dict, str]:
    source_path = source_dir / f"{slug}.apng"
    raw, selected = fetch_candidates(
        source_path, base, gendered(prefix, dex), force
    )
    source_path.write_bytes(raw)
    # These APNGs are commonly encoded at ~60fps. Atlas playback targets 30fps:
    # combine sub-33ms source intervals while retaining their total duration.
    # This also keeps pathological long loops such as Yanma within a 4096px
    # mobile-safe sheet without truncating the animation or speeding it up.
    info = convert(raw, destination / f"{slug}.png", max_dimension=4096,
                   coalesce=True, resample_duration=33,
                   collapse_cycles=True)
    return info, selected


def definition(front: dict, back: dict, slug: str) -> tuple[str, str]:
    front_path = f"assets/battle/front-animated/gen5/shiny/{slug}.png"
    back_path = f"assets/battle/back-animated/gen5/shiny/{slug}.png"
    return (
        f"    front = {lua_definition(front_path, front)},",
        f"    back = {lua_definition(back_path, back, stable_anchor=True)},",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--base-url", default=SOURCE)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()

    front_dir = root / "assets/battle/front-animated/gen5/shiny"
    back_dir = root / "assets/battle/back-animated/gen5/shiny"
    front_source = front_dir / "_source"
    back_source = back_dir / "_source"
    for directory in (front_dir, back_dir, front_source, back_source):
        directory.mkdir(parents=True, exist_ok=True)

    records: list[tuple[str, str, str]] = []
    for number, (name, slug) in enumerate(canonical_roster(root), 1):
        dex = f"{number:03d}"
        front, front_title = import_side(
            front_source, front_dir, args.base_url, "Spr 5b", dex, slug,
            args.force,
        )
        back, back_title = import_side(
            back_source, back_dir, args.base_url, "Spr b 5b", dex, slug,
            args.force,
        )
        front_def, back_def = definition(front, back, slug)
        records.append((name, front_def, back_def))
        print(
            f"[{number:03d}/386] {slug:<12s} "
            f"front={front['frames']:>3d}f ({front_title}); "
            f"back={back['frames']:>3d}f ({back_title})",
            flush=True,
        )

    # The ordinary #386 entry above is Normal Forme. Keep every alternate
    # forme separately so 386S can never replace the archive's bare 386 art.
    for suffix, slug, aliases in (
        ("A", "deoxys-attack", ("DEOXYS_A", "DEOXYS_ATTACK")),
        ("D", "deoxys-defense", ("DEOXYS_D", "DEOXYS_DEFENSE")),
        ("S", "deoxys-speed", ("DEOXYS_S", "DEOXYS_SPEED")),
    ):
        front, front_title = import_side(
            front_source, front_dir, args.base_url, "Spr 5b", f"386{suffix}",
            slug, args.force,
        )
        back, back_title = import_side(
            back_source, back_dir, args.base_url, "Spr b 5b", f"386{suffix}",
            slug, args.force,
        )
        front_def, back_def = definition(front, back, slug)
        records.extend((alias, front_def, back_def) for alias in aliases)
        print(
            f"[386{suffix}] {slug:<14s} front={front['frames']}f "
            f"({front_title}); back={back['frames']}f ({back_title})",
            flush=True,
        )

    lines = [
        "-- Generated by tools/import_gen5_shiny_animated_sprites.py.",
        "-- Black/White shiny animated fronts/backs, National Dex #001-#386.",
        "return {",
    ]
    for name, front_def, back_def in records:
        lines.extend((f"  {name} = {{", front_def, back_def, "  },"))
    lines.append("}")
    metadata = root / "data/animated_battle_sprites_gen5_shiny.lua"
    metadata.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for directory in (front_dir, back_dir):
        files = list(directory.glob("*.png"))
        if len(files) != 389 or any(
            not (directory / name).is_file()
            for name in (
                "bulbasaur.png", "deoxys.png", "deoxys-attack.png",
                "deoxys-defense.png", "deoxys-speed.png",
            )
        ):
            raise RuntimeError(f"incomplete Gen 5 shiny collection in {directory}")
    print(f"wrote 386 species plus three alternate Deoxys formes and {metadata}")


if __name__ == "__main__":
    main()
